# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

[tools]
rojo = "rojo-rbx/rojo@7.5.1"
# rojo = "rojo-rbx/rojo@6.2.0"